### ISSUE TITLE
How to install credentials 

### ISSUE THREAD

**Issue by zhouhao** [trtg/pytwitter#1]
Hi, could you tell me how to install 'credentials'? I couldn't handle it.
Thanks

**Comment by trtg** [comment]
Just create a file named credentials.py in the same directory as everything
else and then the contents of credentials.py should be your consumer key
and secret:

consumer_key="put_your_key_here"
consumer_secret="put_your_secret_here"

**Comment by zhouhao** [comment]
Thanks.
I still have some problem to run you code.
But your code help me a lot, and I have came out some ideas for my project from your code.
Thanks
:+1 : -)
